//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyGUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Cancel {
            get {
                return ResourceManager.GetString("CancelButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton_Create {
            get {
                return ResourceManager.GetString("CreateButton_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_AllFieldsRequired {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new job.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_CreateJob {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing job #{0}.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_EditingJob {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_EditingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton_Delete {
            get {
                return ResourceManager.GetString("DeleteButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DiscardButton_Discard {
            get {
                return ResourceManager.GetString("DiscardButton_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton_Edit {
            get {
                return ResourceManager.GetString("EditButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination folder.
        /// </summary>
        public static string JobCreatePopup_JobDestination {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JobCreatePopup_JobName {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source folder.
        /// </summary>
        public static string JobCreatePopup_JobSource {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup type.
        /// </summary>
        public static string JobCreatePopup_JobType {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string JobState_Copy {
            get {
                return ResourceManager.GetString("JobState_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination structure.
        /// </summary>
        public static string JobState_DestinationStructureCreation {
            get {
                return ResourceManager.GetString("JobState_DestinationStructureCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference calculation.
        /// </summary>
        public static string JobState_DifferenceCalculation {
            get {
                return ResourceManager.GetString("JobState_DifferenceCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string JobState_End {
            get {
                return ResourceManager.GetString("JobState_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string JobState_Paused {
            get {
                return ResourceManager.GetString("JobState_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source scan.
        /// </summary>
        public static string JobState_SourceScan {
            get {
                return ResourceManager.GetString("JobState_SourceScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string JobType_Differential {
            get {
                return ResourceManager.GetString("JobType_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string JobType_Full {
            get {
                return ResourceManager.GetString("JobType_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental.
        /// </summary>
        public static string JobType_Incremental {
            get {
                return ResourceManager.GetString("JobType_Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ResumeButton_Resume {
            get {
                return ResourceManager.GetString("ResumeButton_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton_Settings {
            get {
                return ResourceManager.GetString("SettingsButton_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company software process executable.
        /// </summary>
        public static string SettingsPopup_CompanySoftwareProcess {
            get {
                return ResourceManager.GetString("SettingsPopup_CompanySoftwareProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyCrypto path.
        /// </summary>
        public static string SettingsPopup_EasyCryptoPath {
            get {
                return ResourceManager.GetString("SettingsPopup_EasyCryptoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files extensions to encrypt (without the dot, comma-separated).
        /// </summary>
        public static string SettingsPopup_EncryptedFileTypes {
            get {
                return ResourceManager.GetString("SettingsPopup_EncryptedFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingsPopup_English {
            get {
                return ResourceManager.GetString("SettingsPopup_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        public static string SettingsPopup_French {
            get {
                return ResourceManager.GetString("SettingsPopup_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsPopup_Language {
            get {
                return ResourceManager.GetString("SettingsPopup_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs type.
        /// </summary>
        public static string SettingsPopup_LogType {
            get {
                return ResourceManager.GetString("SettingsPopup_LogType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum size for a file to be &apos;big&apos; (in bytes).
        /// </summary>
        public static string SettingsPopup_MaxFileSize {
            get {
                return ResourceManager.GetString("SettingsPopup_MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority files extensions (without the dot, comma-separated).
        /// </summary>
        public static string SettingsPopup_PriorityFilesExtensions {
            get {
                return ResourceManager.GetString("SettingsPopup_PriorityFilesExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPopup_Settings {
            get {
                return ResourceManager.GetString("SettingsPopup_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption key.
        /// </summary>
        public static string SettingsPopup_XorKey {
            get {
                return ResourceManager.GetString("SettingsPopup_XorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton_Start {
            get {
                return ResourceManager.GetString("StartButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ValidateButton_Validate {
            get {
                return ResourceManager.GetString("ValidateButton_Validate", resourceCulture);
            }
        }
    }
}
