//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyGUI.Resources.Strings.fr", typeof(Strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string CancelButton_Cancel {
            get {
                return ResourceManager.GetString("CancelButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string CreateButton_Create {
            get {
                return ResourceManager.GetString("CreateButton_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champs sont requis.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_AllFieldsRequired {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle tâche.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_CreateJob {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de la tâche #{0}.
        /// </summary>
        public static string CreateJobPopup_PopupTitle_EditingJob {
            get {
                return ResourceManager.GetString("CreateJobPopup_PopupTitle_EditingJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string EditButton_Edit {
            get {
                return ResourceManager.GetString("EditButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier de destination.
        /// </summary>
        public static string JobCreatePopup_JobDestination {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string JobCreatePopup_JobName {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier source.
        /// </summary>
        public static string JobCreatePopup_JobSource {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de sauvegarde.
        /// </summary>
        public static string JobCreatePopup_JobType {
            get {
                return ResourceManager.GetString("JobCreatePopup_JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note : l&apos;application peut ne pas répondre, veuillez ne rien faire.
        /// </summary>
        public static string JobRunPopup_FreezeNote {
            get {
                return ResourceManager.GetString("JobRunPopup_FreezeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exécution de {0} tâche(s).
        /// </summary>
        public static string JobRunPopup_PopupTitle_JobsRunning {
            get {
                return ResourceManager.GetString("JobRunPopup_PopupTitle_JobsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copie.
        /// </summary>
        public static string JobState_Copy {
            get {
                return ResourceManager.GetString("JobState_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure de destination.
        /// </summary>
        public static string JobState_DestinationStructureCreation {
            get {
                return ResourceManager.GetString("JobState_DestinationStructureCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcul de la différence.
        /// </summary>
        public static string JobState_DifferenceCalculation {
            get {
                return ResourceManager.GetString("JobState_DifferenceCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        public static string JobState_End {
            get {
                return ResourceManager.GetString("JobState_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan source.
        /// </summary>
        public static string JobState_SourceScan {
            get {
                return ResourceManager.GetString("JobState_SourceScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Différentielle.
        /// </summary>
        public static string JobType_Differential {
            get {
                return ResourceManager.GetString("JobType_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complète.
        /// </summary>
        public static string JobType_Full {
            get {
                return ResourceManager.GetString("JobType_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incrémentielle.
        /// </summary>
        public static string JobType_Incremental {
            get {
                return ResourceManager.GetString("JobType_Incremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer.
        /// </summary>
        public static string StartButton_Start {
            get {
                return ResourceManager.GetString("StartButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string ValidateButton_Validate {
            get {
                return ResourceManager.GetString("ValidateButton_Validate", resourceCulture);
            }
        }
    }
}
